spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:tcp://localhost/~/frameworkStudy
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true